### ISSUE TITLE
Field with encrypt_key display field value in __repr__ and log as default

### ISSUE THREAD

**Issue by franckbret** [AnyBlok/AnyBlok#108]
When a field has an encrypt_key, its value is unreadable without the key used for encryption on the database table. 
On other side, it is readable in the context of the application (in code or interpreter).
By the way I'm not sure its good pratice to return the non encrypted value into object representation, especially because its what's logged into log files.

Not sure if it's a bug as that behavior can be bypassed easily adding convenient __repr__ and/or __str__ to a model.

What do you think ?

If we consider that its developer responsability to deal with the __repr__ of the model, I'm okay with that and I can write a section into documentation.

**Comment by petrus-v** [comment]
Some through:
* if an hacker can access somehow to some memory spaces I would argue to save the encrypted value as long is possible ! know if the decrypted key is in memory as well that not a lot of benefit.
* does this field could be used with a key given to somelse, I mean an other service could receive encrypted data ? I don't think this is the use case or we would not use that field ?
* also according the context, I guess some time a lazy decrypt would be perfect for performance raison, some times we want to uncrypt all data queried before use them.

So, my 2cts, I guess the best world would be an option to let the dev choose using a lazy decript or not !

**Comment by franckbret** [comment]
@petrus-v Yep, there can be so many use case, but for all case encryption is not the only way for security. Generally speaking it can protect data in case of stolen database only.

For you second point I don't know... I guess yes but never tried.
