### ISSUE TITLE
datetime field that update it's value on write

### ISSUE THREAD

**Issue by franckbret** [AnyBlok/AnyBlok#30]
I need to find a way of updating a datetime value to now, each time the record values change. Something like a last_modified field. How can I achieve this ? Maybe it can be a new kind of field ?

**Comment by jssuzanne** [comment]
Hi in the PR #31 the commit e0960cf[](https://github.com/AnyBlok/AnyBlok/commit/e0960cf7310a7e950c30fe6106fc42b326e55b8c) should resolve your issue.

`update_at = DateTime(auto_update=True)`

This PR will be merged ASAP
