### ISSUE TITLE
AnyblokCore blok pre_migration version analysis

### ISSUE THREAD

**Issue by gracinet** [AnyBlok/AnyBlok#54]
In `AnyblokCore.pre_migration()` there's a direct comparison of versions as simple strings:

```[Python]
    def pre_migration(self, latest_version):
      if latest_version is not None and latest_version < '0.4.1':
```
of course it's wrong. I don't know if it's the proper time to come up with a generic magical solution involving, e.g, the version representation in `pkg_resources` that surely follows PEP 440 (do we really want to depend on that ?), but at least this case should be fixed.

**Comment by jssuzanne** [comment]
+1

The same error exists for the methods

- post_migration
- update
