### ISSUE TITLE
Blok.pre_migration() called after creation of new tables 

### ISSUE THREAD

**Issue by gracinet** [AnyBlok/AnyBlok#55]
I'm writing a `pre_migration()` method on a Blok,  for a few Model renames (see https://github.com/AnyBlok/anyblok_wms_base/pull/17), was thinking a simple `ALTER TABLE … RENAME TO` would be enough, but actually the new tables are already created.

So, in short `pre_migration()` is not really before the migration (unless creation of tables is not considered to be part of migrating a DB?)

**Comment by jssuzanne** [comment]
Released in 0.20.0
