### ISSUE TITLE
In some cases, rollback is not done between two tests.

### ISSUE THREAD

**Issue by GohuHQ** [AnyBlok/AnyBlok#59]
https://github.com/AnyBlok/AnyBlok/blob/b2c1a086309d4e6717f924826ce60fc7177a5a91/anyblok/tests/testcase.py#L404
@jssuzanne : As you told me, if we add `self.registry.unittest_transaction.rollback()`, it works.

**Comment by jssuzanne** [comment]
This issue seem close
