### ISSUE TITLE
Flagging an AnyBlok field as modified

### ISSUE THREAD

**Issue by gracinet** [AnyBlok/AnyBlok#72]
In some cases, a field might correspond to a mutable Python structure, such as a `dict`. Changing the contents of that data structure is invisible to SQLAlchemy unless one calls `flag_modified()`.

I'm doing this for example in Anyblok / WMS Base for the `flexible` JSONB field of `Model.Wms.PhysObj.Properties`: (taken from https://github.com/AnyBlok/anyblok_wms_base/blob/master/anyblok_wms_base/core/physobj/main.py#L484)

```python
          from sqlalchemy.orm.attributes import flag_modified
          self.flexible[k] = v
          flag_modified(self, '__anyblok_field_flexible')
```

The problem here is that it makes appicative code (AWB in that case) rely on AnyBlok internals (actual name of the attribute as seen from SQLAlchemy).

Therefore it would be a good thing for AnyBlok to expose its own version of `flag_modified`, so that I could do simply:

```python
     from anyblok.field import flag_modified
     self.flexible[k] = v
     flag_modified(self, 'flexible')
````

**Comment by jssuzanne** [comment]
I prefere
```
self.flag_modified('flexible')
```

The method on the **Model** could be

```
def flag_modified(self, *fields):
    ...
```

The goal is to keep the same partern as [refresh](https://github.com/AnyBlok/AnyBlok/blob/master/anyblok/bloks/anyblok_core/core/sqlbase.py#L533>) or [expire](https://github.com/AnyBlok/AnyBlok/blob/master/anyblok/bloks/anyblok_core/core/sqlbase.py#L545)

**Comment by gracinet** [comment]
@jssuzanne thanks for your reply. Well that's what I didn't dare to suggest (didn't know about `refresh()` and `expire()` methods either)
