### ISSUE TITLE
MySQL: ShareDataTestCase doesn't work

### ISSUE THREAD

**Issue by jssuzanne** [AnyBlok/AnyBlok#96]

**Comment by jssuzanne** [comment]
Because, MySQL and MariaDB do implicite commit, so rollaback is not availlable

**Comment by petrus-v** [comment]
what's the idea, to fix that ? create an other template database which would be the base for shared tests ?

**Comment by jssuzanne** [comment]
I do not think so, it's strongly related to nose. The framework tests are passed in pytest, I do not know if we have to maintain this functionality and up to what point.

Moreover it is also related only to MySQL and MariaDB.
